# this file was changed
dino:
  head_n_prototypes: 131072
  head_bottleneck_dim: 384
ibot:
  separate_head: true
  head_n_prototypes: 131072
train:
  batch_size_per_gpu: 1 # standard is 32
  dataset_path: CustomImageDataset:split=TRAIN:root=/home/ubuntu/example_image/tiling_previews_1024px_0mpp_2.0xdown_normal_heartcenter_munich:extra=/home/ubuntu/example_image/file_list.csv #ImageNet:split=TRAIN:root=/home/ubuntu/example_image/one_test_image:extra=/home/ubuntu/example_image/one_test_image # original is: ImageNet22k
  centering: sinkhorn_knopp
student:
  arch: vit_large
  patch_size: 14
  drop_path_rate: 0.4
  ffn_layer: swiglufused
  block_chunks: 4
teacher:
  momentum_teacher: 0.994
optim:
  epochs: 500
  weight_decay_end: 0.2
  base_lr: 2.0e-04  # learning rate for a batch size of 1024
  warmup_epochs: 80
  layerwise_decay: 1.0
crops:
  local_crops_size: 98